# Based on https://docs.influxdata.com/telegraf/v1.9/introduction/installation/

---
 - name: Add InfluxDB’s official GPG key
   shell: curl -sL https://repos.influxdata.com/influxdb.key | apt-key add -

 - name: Add InfluxDB’s official repository
   shell: source /etc/lsb-release && echo "deb https://repos.influxdata.com/${DISTRIB_ID,,} ${DISTRIB_CODENAME} stable" | sudo tee /etc/apt/sources.list.d/influxdb.list

 - name: Run apt-get update
   apt:
     update_cache: yes

 - name: Install the latest version of Telegraf
   apt:
     name: telegraf

 - name: Copy the Telegraf configuration file
   template:
     src: telegraf.conf.j2
     dest: /etc/telegraf/telegraf.conf
     backup: yes

 - name: Start and enable the Telegraf service
   systemd:
     enabled: yes
     state: started
     name: telegraf