# Based on https://docs.influxdata.com/telegraf/v1.9/introduction/installation/

---
 - name: Shell | Add InfluxDB’s official GPG key
   shell: curl -sL https://repos.influxdata.com/influxdb.key | apt-key add -

 - name: Shell | Add InfluxDB’s official repository
   shell: add-apt-repository "deb https://repos.influxdata.com/ubuntu $(lsb_release -cs) stable"

 - name: APT | Run apt-get update
   apt:
     update_cache: yes

 - name: APT | Install the latest version of Telegraf
   apt:
     name: telegraf

 - name: Systemd | Enable the Telegraf service
   systemd:
     enabled: yes
     name: telegraf

 - name: Template | Copy the Telegraf configuration file
   template:
     src: telegraf.conf.j2
     dest: /etc/telegraf/telegraf.conf
     backup: yes
   notify: restart telegraf
