#Based on http://docs.grafana.org/installation/docker/

---
 - name: Create
   docker_container:
    name: grafana
    image: grafana/grafana
    ports:
     - "3000:3000"
    env:
        GF_SECURITY_ADMIN_PASSWORD:{{ gf_secutiry_admin_password }}