---
 - name: Create directory
   file: 
    path: /opt/grafana
    state: directory

 - name: Copy docker-compose.yml
   template:
     src: docker-compose.yml.j2
     dest: /opt/grafana/docker-compose.yml

 - name: Docker-compose up container
   shell: docker-compose up -d
   args:
     chdir: /opt/grafana