---
 - name: User | Add InfluxDB user
   user:
    name: "{{ influx_sys_user }}"
    uid: 4000
    shell: /bin/false
    create_home: yes
    home: "{{ influx_path }}"

 - name: File | Create directory
   file: 
    path: "{{ item }}"
    state: directory
    owner: "{{ influx_sys_user }}"
    group: "{{ influx_sys_user }}"
    mode: 0750
   with_items:
     - "{{ influx_volume_data }}"

 - name: Template | Copy docker-compose.yml
   template:
     src: docker-compose.yml.j2
     dest: "{{ influx_path }}/docker-compose.yml"

 - name: Shell | Docker-compose up container
   shell: docker-compose up -d
   args:
     chdir: "{{ influx_path }}"
