# Based on https://docs.docker.com/install/linux/docker-ce/ubuntu/
#          https://docs.docker.com/compose/install/

---
 - name: Docker | Run apt-get update
   apt:
     update_cache: yes

 - name: Uninstall old versions
   apt:
     name: "{{ packages }}"
     state: absent
   vars:
     packages:
     - docker
     - docker-engine
     - docker.io
     - containerd 
     - runc

 - name: Docker | Install packages to allow apt to use a repository over HTTPS
   apt:
     name: "{{ packages }}"
   vars:
     packages:
     - apt-transport-https
     - ca-certificates 
     - curl
     - gnupg2
     - software-properties-common

 - name: Docker | Add Docker’s official GPG key
   shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

 - name: Docker | Add Docker’s official repository
   shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

 - name: Run apt-get update
   apt:
     update_cache: yes

 - name: Docker | Install the latest version of Docker CE
   apt:
     name: docker-ce 

 - name: Docker | Download Docker Compose
   shell: curl -L "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-$(uname -s)-$(uname -m)" -o "{{ docker_compose_path }}"

 - name: Docker | Apply executable permissions to the binary docker-compose
   file:
     path: "{{ docker_compose_path }}"
     owner: root
     group: root
     mode: 0750
