---
 - name: Configure server monitor
   hosts: docker
   remote_user: root
   roles:
     - { role: docker, when: docker_deploy }
     - { role: influxdb, when: influx_deploy }
     - { role: grafana, when: grafana_deploy }
   tags:
     - stack

 - name: Configure Telegraf service
   hosts: monitoring
   remote_user: root
   roles:
     - telegraf
   tags:
     - telegraf
